keys:
  - &host age1x9s5527ghndlmjshulcxf7325pnf5knp8wldzdj4f2mvpn4e533qxwzzex
  - &user age1exfacum7j8t9e326xlnl506fr7d0uq3uhsu3pad40jmxyr6c3azsg0e6ju

creation_rules:
  - path_override: secrets.yaml
    key_groups:
      - age:
          - *host
          - *user
